name: Java CI

on:
  release:
    types: [ created ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/nuclei-burp-plugin-1.1.3-SNAPSHOT-jar-with-dependencies.jar #update version before release
          asset_name: nuclei-burp-plugin-1.1.3.jar #update version before release
          asset_content_type: application/java-archive